# Generated by Django 4.2.5 on 2023-09-20 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_products_date_creation_products_en_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='en_promotion',
        ),
    ]
